using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Text;
using System.Threading.Tasks;
using Verse;

namespace RimDialogue.Core
{
  [Serializable]
  public class DialogueData
  {
    public string clientId = String.Empty;
    public string specialInstructions = String.Empty;
    public int maxWords = -1;
    public string interaction = String.Empty;
    public string scenario = string.Empty;
    public int daysPassedSinceSettle = -1;
    public string biome = String.Empty;
    public bool isOutside = false;
    public string room = String.Empty;
    public float roomCleanliness = -1f;
    public float roomImpressiveness = -1f;
    public string currentWeather = String.Empty;
    public float outdoorTemp = -1f;
    public float wealthTotal = -1f;
    public float foodTotal = -1f;
    public int defensesTotal = -1;
    public int medicineTotal = -1;
    public int drugsTotal = -1;
    public int colonistsCount = -1;
    public int prisonersCount = -1;
    public string[] recentIncidents = [];
    public string initiatorThingID = String.Empty;
    public string initiatorFullName = String.Empty;
    public string initiatorCarrying = String.Empty;
    public string initiatorNickName = String.Empty;
    public string initiatorJobReport = String.Empty;
    public string initiatorRoyaltyTitle = string.Empty;
    public string initiatorGender = String.Empty; 
    public string initiatorFactionName = String.Empty;
    public string initiatorFactionLabel = String.Empty;
    public string initiatorFactionDescription = String.Empty;
    public string initiatorDescription = String.Empty;
    public string initiatorRace = String.Empty;
    public int initiatorAge = -1;
    public string initiatorBeard = string.Empty;
    public string initiatorHair = string.Empty;
    public string initiatorFaceTattoo = string.Empty;
    public string initiatorBodyTattoo = string.Empty;
    public string initiatorIdeologyName = string.Empty;
    public string initiatorIdeologyDescription = String.Empty;
    public string[] initiatorIdeologyPrecepts = [];
    public bool initiatorIsColonist = false;
    public bool initiatorIsPrisoner = false;
    public bool initiatorIsHostile = false;
    public bool initiatorIsCreepJoiner = false;
    public bool initiatorIsGhoul = false;
    public bool initiatorIsBloodFeeder = false;
    public bool initiatorIsSlave = false;
    public bool initiatorIsAnimal = false;
    public string[] initiatorSkills = [];
    public string[] initiatorTraits = [];
    public string initiatorChildhood = String.Empty;
    public string initiatorAdulthood = String.Empty;
    public string[] initiatorRelations = [];
    public string[] initiatorApparel = [];
    public string[] initiatorWeapons = [];
    public string[] initiatorHediffs = [];
    public int initiatorOpinionOfRecipient = 0;
    public string[] initiatorMoodThoughts = [];
    public string initiatorMoodString = string.Empty;
    public float initiatorMoodPercentage = -1f;
    public float initiatorComfortPercentage = -1f;
    public float initiatorFoodPercentage = -1f;
    public float initiatorRestPercentage = -1f;
    public float initiatorJoyPercentage = -1f;
    public float initiatorBeautyPercentage = -1f;
    public float initiatorDrugsDesirePercentage = -1f;
    public float initiatorEnergyPercentage = -1f;
    public string recipientThingID = String.Empty;
    public string recipientFullName = String.Empty;
    public string recipientJobReport = String.Empty;
    public string recipientCarrying = String.Empty;
    public string recipientNickName = String.Empty;
    public string recipientRoyaltyTitle = string.Empty;
    public string recipientGender = string.Empty;
    public string recipientFactionName = String.Empty;
    public string recipientFactionLabel = String.Empty;
    public string recipientFactionDescription = String.Empty;
    public string recipientDescription = String.Empty;
    public string recipientRace = String.Empty;
    public int recipientAge = -1;
    public string recipientHair = string.Empty;
    public string recipientFaceTattoo = string.Empty;
    public string recipientBodyTattoo = string.Empty;
    public string recipientBeard = string.Empty;
    public string recipientIdeologyName = string.Empty;
    public string recipientIdeologyDescription = String.Empty;
    public string[] recipientIdeologyPrecepts = [];
    public bool recipientIsColonist = false;
    public bool recipientIsPrisoner = false;
    public bool recipientIsHostile = false;
    public bool recipientIsCreepJoiner = false;
    public bool recipientIsGhoul = false;
    public bool recipientIsBloodfeeder = false;
    public bool recipientIsSlave = false;
    public bool recipientIsAnimal = false;
    public string[] recipientSkills = [];
    public string[] recipientTraits = [];
    public string recipientChildhood = String.Empty;
    public string recipientAdulthood = String.Empty;
    public string[] recipientRelations = [];
    public string[] recipientApparel = [];
    public string[] recipientWeapons = [];
    public string[] recipientHediffs = [];
    public int recipientOpinionOfInitiator = 0;
    public string[] recipientMoodThoughts = [];
    public string recipientMoodString = string.Empty;
    public float recipientMoodPercentage;
    public float recipientComfortPercentage;
    public float recipientFoodPercentage;
    public float recipientRestPercentage;
    public float recipientJoyPercentage;
    public float recipientBeautyPercentage;
    public float recipientDrugsDesirePercentage;
    public float recipientEnergyPercentage;
  }


}
